### ISSUE TITLE
Remove constraint that isPrimary be present for determinations

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/natural-history-collection-api#273]
It looks as if the client *must* indicate that at least one of the their determinations in an array as `isPrimary`. However, there is not always a primary determination such as in Mixed Samples where each determination is equal – these are all different organisms. In a Whole Organism Material Sample, it is indeed useful to have a primary determination because their determinations are in a temporal sequence. See also #272.

So...

When the Material Sample type == "Mixed Sample", relax constraint that at least one of the determinations has `isPrimary` set to true.

**Comment by cgendreau** [comment]
Solved by changes where Determination is now under Organism.
