### ISSUE TITLE
Change to isFiledAs

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/natural-history-collection-api#314]
https://github.com/AAFC-BICoE/natural-history-collection-api/blob/f3ce4823f5c7ab5864a295d2ac730e4cb650882c/src/main/java/ca/gc/aafc/collection/api/entities/Determination.java#L84

Unlike the above, the API spec has this attribute entitled, `isFiledAs` (with a 'd') not `isFileAs`.

**Comment by cgendreau** [comment]
Fixed, will be included with 0.54
