### ISSUE TITLE
Increase acceptable verbatimDeterminer length

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/natural-history-collection-api#391]
I have a value:

`Shawkat Ali, Paul D. Hildebrand, Willy E. Renderos, and Pervaiz A. Abbasi (Kentville Research and Development Centre, Agriculture and Agri-Food Canada)`

...in a data source that I would like put in `verbatimDeterminer` (found in a determination of organism in a material sample). Can we increase its acceptable string length?

**Comment by cgendreau** [comment]
done
