### ISSUE TITLE
Update endpoint for storageUnitUsage

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/natural-history-collection-api#463]
The OpenAPI endpoint for storage unit usage still points to /v1/storageUnitCoordinates, https://dina-web.github.io/collection-specs/#tag/Storage-Unit-Usage

**Comment by cgendreau** [comment]
Fixed by https://github.com/DINA-Web/collection-specs/commit/971685190505ceb9c828642d566f90ce2b7e0620
